
# Tomcat Server

server:
  port: 8080


# Logger

logging.level.com:
  busyqa.course: DEBUG
  org.hibernate.type: INFO

# Profile
 
spring:
  profiles:
    active: default
    
# Banner Text

  banner:
    charset: UTF-8
    location: classpath:/banner/busyQA.txt

# Jackson Settings

  jackson:
    date-format: "dd-MM-yyyy"
        
# Database Settings

  datasource:
    url: jdbc:mysql://busyqa-db.c8cpvhykwie9.us-east-2.rds.amazonaws.com:3306/usersdb?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 15
      max-idle: 10
      initial-size: 3
      test-on-borrow: true
    continue-on-error: false
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
        use-new-id-generator-mappings: true
        dialect: org.hibernate.dialect.MySQLDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

#     url: jdbc:mysql://localhost:3306/usersdb?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#     username: root
#     password: root